# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


f = lambda d: d[0] + d[1]
fib = [1, 2]
i = f(fib[-2:])
fib.append(i)
while i < 4000000:
    i = f(fib[-2:])
    fib.append(i)
print(sum(fib[1::3]))
